Checking if there are any changes after adding node properties

In [1]:
import json
import sys
from mrtparse import *
import networkx as nx
import matplotlib.pyplot as plt

import os
import requests
import gzip
import shutil

from neo4j import GraphDatabase

In [2]:
from langchain.chat_models import ChatOpenAI
from langchain.chains import GraphCypherQAChain
from langchain.graphs import Neo4jGraph

In [3]:
import langchain

In [4]:
graph = Neo4jGraph(
    url="neo4j+s://28e5b287.databases.neo4j.io",
    username="neo4j",
    password="z9J3DPCCxGYELn99XDdFbFIBnWOwR5fdn4MiG_Nvdck"
)

In [5]:
import os
name = 'OPENAI_API_KEY'

key_location = "/Users/kiranjyothisheena/Documents/Kiran_Files/Capstone/OpenAPI_Key"
key_file = open(key_location, "r")
openapi_key = key_file.readline()

#secret = getpass.getpass("Enter the OpenAI API Key")
os.environ[name] = openapi_key
print(f"Have successfully set up {name} as an environment variable.")

Have successfully set up OPENAI_API_KEY as an environment variable.


In [6]:
langchain.debug = False

In [7]:
# Setting up ChatGPT integration with Graph Database
chain = GraphCypherQAChain.from_llm(
    ChatOpenAI(temperature=0), graph=graph, verbose=True,
)
    

## Find a path between two nodes

MATCH path = (n:Node {id: '2519'})-[:CONNECTS*]->(m:Node {id: '10026'}) <br>
RETURN path

In [9]:
chain.run("""
What is a path from node 56203 to node 38803 for nodes of type node?
""")



> Entering new GraphCypherQAChain chain...
Generated Cypher:
MATCH path = (n:Node {id: '56203'})-[:CONNECTS*]->(m:Node {id: '38803'})
RETURN path
Full Context:
[{'path': [{'country': 'AU', 'id': '56203', 'org_name': 'Wirefreebroadband Pty Ltd', 'as_name': 'Gtelecom-AUSTRALIA'}, 'CONNECTS', {'country': 'AU', 'upstream': '2', 'downstream': '0', 'rank': '9740', 'id': '38803', 'org_name': 'Wirefreebroadband Pty Ltd', 'as_name': 'WPL-AS-AP'}]}]

> Finished chain.


'A path from node 56203 to node 38803 for nodes of type node is established through the organization Wirefreebroadband Pty Ltd. The path starts with the Gtelecom-AUSTRALIA AS (Autonomous System) and connects to the Wirefreebroadband Pty Ltd AS (WPL-AS-AP).'

In [12]:
chain.run("""
What is a path from node 56203 to node 38803 for nodes of type node?
""")



> Entering new GraphCypherQAChain chain...
Generated Cypher:
MATCH path = (n:Node {id: '56203'})-[:CONNECTS*]->(m:Node {id: '38803'})
RETURN path
Full Context:
[{'path': [{'country': 'AU', 'id': '56203', 'org_name': 'Wirefreebroadband Pty Ltd', 'as_name': 'Gtelecom-AUSTRALIA'}, 'CONNECTS', {'country': 'AU', 'upstream': '2', 'downstream': '0', 'rank': '9740', 'id': '38803', 'org_name': 'Wirefreebroadband Pty Ltd', 'as_name': 'WPL-AS-AP'}]}]

> Finished chain.


'A path from node 56203 to node 38803 for nodes of type node is established through the organization Wirefreebroadband Pty Ltd. The path starts with the Gtelecom-AUSTRALIA AS (Autonomous System) and connects to the Wirefreebroadband Pty Ltd AS (WPL-AS-AP).'

In [11]:
chain.run("""
What is a path from node 2519 to node 10026 for nodes of type node?
""")



> Entering new GraphCypherQAChain chain...
Generated Cypher:
MATCH path = (n:Node {id: '2519'})-[:CONNECTS*]->(m:Node {id: '10026'})
RETURN path
Full Context:
[{'path': [{'country': 'JP', 'upstream': '3', 'downstream': '64', 'rank': '314', 'id': '2519', 'as_name': 'VECTANT'}, 'CONNECTS', {'country': 'AU', 'id': '10026', 'org_name': 'Telstra International Limited', 'as_name': 'TELSTRAGLOBAL'}]}]

> Finished chain.


'A path from node 2519 to node 10026 for nodes of type node is formed by the AS (Autonomous System) called VECTANT in Japan, which has 3 upstream connections and 64 downstream connections. This AS is connected to Telstra International Limited in Australia, which has the AS name TELSTRAGLOBAL.'

In [13]:
chain.run("""
What is a path from node 2519 to node 10026 for nodes of type node_2?
""")



> Entering new GraphCypherQAChain chain...
Generated Cypher:
MATCH path = (n:Node_2 {id: '2519'})-[:CONNECTS_2*]->(m:Node_2 {id: '10026'})
RETURN path
Full Context:
[{'path': [{'country': 'JP', 'upstream': '3', 'downstream': '64', 'rank': '314', 'id': '2519', 'as_name': 'VECTANT'}, 'CONNECTS_2', {'country': 'AU', 'upstream': '2', 'downstream': '225', 'rank': '61', 'id': '1221', 'org_name': 'Telstra Corporation Limited', 'as_name': 'ASN-TELSTRA'}, 'CONNECTS_2', {'country': 'AU', 'upstream': '2', 'downstream': '0', 'rank': '9740', 'id': '38803', 'org_name': 'Wirefreebroadband Pty Ltd', 'as_name': 'WPL-AS-AP'}, 'CONNECTS_2', {'country': 'AU', 'upstream': '8', 'downstream': '437', 'rank': '920', 'id': '4826', 'org_name': 'VOCUS PTY LTD', 'as_name': 'VOCUS-BACKBONE-AS'}, 'CONNECTS_2', {'country': 'AU', 'upstream': '3', 'downstream': '193', 'rank': '3029', 'id': '4608', 'org_name': 'Asia Pacific Network Information Centre', 'as_name': 'APNIC-SERVICES'}, 'CONNECTS_2', {'country': 'AU', 'id'

'A path from node 2519 to node 10026 for nodes of type node_2 is as follows: VECTANT (JP) -> Telstra Corporation Limited (AU) -> Wirefreebroadband Pty Ltd (AU) -> VOCUS PTY LTD (AU) -> Asia Pacific Network Information Centre (AU) -> Telstra International Limited (AU).'

In [14]:
chain.run("""
What is a path from node 2519 to node 1 for nodes of type node?
""")



> Entering new GraphCypherQAChain chain...
Generated Cypher:
MATCH path = (n:Node {id: '2519'})-[:CONNECTS*]->(m:Node {id: '1'})
RETURN path
Full Context:
[]

> Finished chain.


"I'm sorry, but I don't have the information to answer your question."

## Find number of paths

MATCH path = (n:Node {id: '2519'})-[:CONNECTS*]->(m:Node {id: '10026'}) <br>
RETURN count(path)

In [15]:
chain.run("""
How many path exists from node 56203 to node 38803 for nodes of type node?
""")



> Entering new GraphCypherQAChain chain...
Generated Cypher:
MATCH (n:Node {id: '56203'}), (m:Node {id: '38803'})
MATCH path = (n)-[:CONNECTS*]->(m)
RETURN count(path)
Full Context:
[{'count(path)': 1}]

> Finished chain.


'There is 1 path that exists from node 56203 to node 38803 for nodes of type node.'

In [16]:
chain.run("""
How many path exists from node 2519 to node 10026 for nodes of type node?
""")



> Entering new GraphCypherQAChain chain...
Generated Cypher:
MATCH (n:Node {id: '2519'}), (m:Node {id: '10026'})
MATCH path = (n)-[:CONNECTS*]->(m)
RETURN count(path)
Full Context:
[{'count(path)': 1}]

> Finished chain.


'There is 1 path that exists from node 2519 to node 10026 for nodes of type node.'

In [14]:
chain.run("""
How many paths exists from node 2519 to node 10026 for nodes of type node_2?
""")
## This is wrong



> Entering new GraphCypherQAChain chain...
Generated Cypher:
MATCH (n:Node_2 {id: '2519'})-[*]->(m:Node_2 {id: '10026'})
RETURN COUNT(DISTINCT n)
Full Context:
[{'COUNT(DISTINCT n)': 1}]

> Finished chain.


'There is 1 path that exists from node 2519 to node 10026 for nodes of type node_2.'

## Return all the paths

In [15]:
chain.run("""
Return all paths from node 2519 to node 10026 for nodes of type node_2?
""")



> Entering new GraphCypherQAChain chain...
Generated Cypher:
MATCH path = (n:Node_2 {id: '2519'})-[:CONNECTS_2*]->(m:Node_2 {id: '10026'})
RETURN path
Full Context:
[{'path': [{'country': 'JP', 'upstream': '3', 'downstream': '64', 'rank': '314', 'id': '2519', 'as_name': 'VECTANT'}, 'CONNECTS_2', {'country': 'AU', 'upstream': '2', 'downstream': '225', 'rank': '61', 'id': '1221', 'org_name': 'Telstra Corporation Limited', 'as_name': 'ASN-TELSTRA'}, 'CONNECTS_2', {'country': 'AU', 'upstream': '2', 'downstream': '0', 'rank': '9740', 'id': '38803', 'org_name': 'Wirefreebroadband Pty Ltd', 'as_name': 'WPL-AS-AP'}, 'CONNECTS_2', {'country': 'AU', 'upstream': '8', 'downstream': '437', 'rank': '920', 'id': '4826', 'org_name': 'VOCUS PTY LTD', 'as_name': 'VOCUS-BACKBONE-AS'}, 'CONNECTS_2', {'country': 'AU', 'upstream': '3', 'downstream': '193', 'rank': '3029', 'id': '4608', 'org_name': 'Asia Pacific Network Information Centre', 'as_name': 'APNIC-SERVICES'}, 'CONNECTS_2', {'country': 'AU', 'id'

KeyboardInterrupt: 

In [ ]:
chain.run("""
Return all paths from node 4651 to node 1136 for nodes of type node_2?
""")

## Shortest Path

In [32]:
chain.run("""
What is the shortest path from node 2519 to node 10026 for nodes of type node?
""")



> Entering new GraphCypherQAChain chain...
Generated Cypher:
MATCH (n:Node {id: '2519'}), (m:Node {id: '10026'})
MATCH path = shortestPath((n)-[:CONNECTS*]-(m))
RETURN path
Full Context:
[{'path': [{'id': '2519'}, 'CONNECTS', {'id': '10026'}]}]

> Finished chain.


'The shortest path from node 2519 to node 10026 for nodes of type node is through the connection labeled "CONNECTS".'

In [33]:
chain.run("""
What is the shortest path from node 2519 to node 10026 for nodes of type node_2?
""")



> Entering new GraphCypherQAChain chain...
Generated Cypher:
MATCH (n:Node_2 {id: '2519'}), (m:Node_2 {id: '10026'})
MATCH path = shortestPath((n)-[:CONNECTS_2*]-(m))
RETURN path
Full Context:
[{'path': [{'id': '2519'}, 'CONNECTS_2', {'id': '1221'}, 'CONNECTS_2', {'id': '4608'}, 'CONNECTS_2', {'id': '10026'}]}]

> Finished chain.


'The shortest path from node 2519 to node 10026 for nodes of type node_2 is through the following nodes: 2519 -> 1221 -> 4608 -> 10026.'

In [8]:
chain.run("""
What is the shortest path from node 2519 to node 10026 for nodes of type node_2?
""")



> Entering new GraphCypherQAChain chain...
Generated Cypher:
MATCH (n:Node_2 {id: '2519'}), (m:Node_2 {id: '10026'})
MATCH path = shortestPath((n)-[:CONNECTS_2*]-(m))
RETURN path
Full Context:
[{'path': [{'country': 'JP', 'upstream': '3', 'downstream': '64', 'rank': '314', 'id': '2519', 'as_name': 'VECTANT'}, 'CONNECTS_2', {'country': 'AU', 'upstream': '2', 'downstream': '225', 'rank': '61', 'id': '1221', 'org_name': 'Telstra Corporation Limited', 'as_name': 'ASN-TELSTRA'}, 'CONNECTS_2', {'country': 'AU', 'upstream': '3', 'downstream': '193', 'rank': '3029', 'id': '4608', 'org_name': 'Asia Pacific Network Information Centre', 'as_name': 'APNIC-SERVICES'}, 'CONNECTS_2', {'country': 'AU', 'id': '10026', 'org_name': 'Telstra International Limited', 'as_name': 'TELSTRAGLOBAL'}]}]

> Finished chain.


'The shortest path from node 2519 to node 10026 for nodes of type node_2 is through the following nodes: VECTANT, ASN-TELSTRA, APNIC-SERVICES, and TELSTRAGLOBAL.'

In [10]:
chain.run("""
What is the shortest path from node 2519 to node 10026 for nodes of type node_2? Specify the path in terms of
node id.
""")



> Entering new GraphCypherQAChain chain...
Generated Cypher:
MATCH (n:Node_2 {id: '2519'}), (m:Node_2 {id: '10026'})
MATCH path = shortestPath((n)-[:CONNECTS_2*]-(m))
RETURN [node in nodes(path) | node.id] AS path_ids
Full Context:
[{'path_ids': ['2519', '1221', '4608', '10026']}]

> Finished chain.


'The shortest path from node 2519 to node 10026 for nodes of type node_2 is through the following nodes: 2519, 1221, 4608, and 10026.'

## Checks

In [21]:
chain.run("""
What is the longest existing path for nodes of type node_2?
""")

[chain/start] [1:chain:GraphCypherQAChain] Entering Chain run with input:
{
  "query": "\nWhat is the longest existing path for nodes of type node_2?\n"
}
[chain/start] [1:chain:GraphCypherQAChain > 2:chain:LLMChain] Entering Chain run with input:
{
  "question": "\nWhat is the longest existing path for nodes of type node_2?\n",
  "schema": "Node properties are the following: \n {'Node': [{'property': 'id', 'type': 'STRING'}], 'Node_2': [{'property': 'id', 'type': 'STRING'}]}\nRelationships properties are the following: \n {}\nRelationships are: \n['(:Node)-[:CONNECTS]->(:Node)', '(:Node_2)-[:CONNECTS_2]->(:Node_2)']"
}
[llm/start] [1:chain:GraphCypherQAChain > 2:chain:LLMChain > 3:llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "Human: Task:Generate Cypher statement to query a graph database.\nInstructions:\nUse only the provided relationship types and properties in the schema.\nDo not use any other relationship types or properties that are not provided.\nSchema:\nNo

'The longest existing path for nodes of type node_2 is the path that connects node 23969 to node 57821.'

In [11]:
chain.run("""
What is the longest path from 23969 to 57821 for nodes of type node_2? Specify the path in terms of
node id.
""")



> Entering new GraphCypherQAChain chain...


KeyboardInterrupt: 

## Custom

In [25]:
chain.run("""
Does a path exist from node 56203 to node 38803 for nodes of type node? If so what is the path?
""")



> Entering new GraphCypherQAChain chain...
Generated Cypher:
MATCH path = (n:Node {id: '56203'})-[:CONNECTS*]->(m:Node {id: '38803'})
RETURN path
Full Context:
[{'path': [{'id': '56203'}, 'CONNECTS', {'id': '38803'}]}]

> Finished chain.


'Yes, a path exists from node 56203 to node 38803 for nodes of type node. The path is: 56203 -> 38803.'

In [31]:
chain.run("""
Does a path exist from node 56203 to node 38803 for nodes of type node? If so what is the path?
""")

[chain/start] [1:chain:GraphCypherQAChain] Entering Chain run with input:
{
  "query": "\nDoes a path exist from node 56203 to node 38803 for nodes of type node? If so what is the path?\n"
}
[chain/start] [1:chain:GraphCypherQAChain > 2:chain:LLMChain] Entering Chain run with input:
{
  "question": "\nDoes a path exist from node 56203 to node 38803 for nodes of type node? If so what is the path?\n",
  "schema": "Node properties are the following: \n {'Node': [{'property': 'id', 'type': 'STRING'}], 'Node_2': [{'property': 'id', 'type': 'STRING'}]}\nRelationships properties are the following: \n {}\nRelationships are: \n['(:Node)-[:CONNECTS]->(:Node)', '(:Node_2)-[:CONNECTS_2]->(:Node_2)']"
}
[llm/start] [1:chain:GraphCypherQAChain > 2:chain:LLMChain > 3:llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "Human: Task:Generate Cypher statement to query a graph database.\nInstructions:\nUse only the provided relationship types and properties in the schema.\nDo not use any ot

'Yes, a path exists from node 56203 to node 38803 for nodes of type node. The path is: 56203 -> 38803.'

In [30]:
chain.run("""
Does a path exist from node 2519 to node 18144 for nodes of type node? If so what is the path?
""")

[chain/start] [1:chain:GraphCypherQAChain] Entering Chain run with input:
{
  "query": "\nDoes a path exist from node 2519 to node 18144 for nodes of type node? If so what is the path?\n"
}
[chain/start] [1:chain:GraphCypherQAChain > 2:chain:LLMChain] Entering Chain run with input:
{
  "question": "\nDoes a path exist from node 2519 to node 18144 for nodes of type node? If so what is the path?\n",
  "schema": "Node properties are the following: \n {'Node': [{'property': 'id', 'type': 'STRING'}], 'Node_2': [{'property': 'id', 'type': 'STRING'}]}\nRelationships properties are the following: \n {}\nRelationships are: \n['(:Node)-[:CONNECTS]->(:Node)', '(:Node_2)-[:CONNECTS_2]->(:Node_2)']"
}
[llm/start] [1:chain:GraphCypherQAChain > 2:chain:LLMChain > 3:llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "Human: Task:Generate Cypher statement to query a graph database.\nInstructions:\nUse only the provided relationship types and properties in the schema.\nDo not use any othe

"I'm sorry, but I don't have the information to answer your question."

## Recheck

In [9]:
chain.run("""
Return all paths from node 2519 to node 10026 for nodes of type node_2?
""")

[chain/start] [1:chain:GraphCypherQAChain] Entering Chain run with input:
{
  "query": "\nReturn all paths from node 2519 to node 10026 for nodes of type node_2?\n"
}
[chain/start] [1:chain:GraphCypherQAChain > 2:chain:LLMChain] Entering Chain run with input:
{
  "question": "\nReturn all paths from node 2519 to node 10026 for nodes of type node_2?\n",
  "schema": "Node properties are the following: \n {'Node': [{'property': 'id', 'type': 'STRING'}], 'Node_2': [{'property': 'id', 'type': 'STRING'}]}\nRelationships properties are the following: \n {}\nRelationships are: \n['(:Node)-[:CONNECTS]->(:Node)', '(:Node_2)-[:CONNECTS_2]->(:Node_2)']"
}
[llm/start] [1:chain:GraphCypherQAChain > 2:chain:LLMChain > 3:llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "Human: Task:Generate Cypher statement to query a graph database.\nInstructions:\nUse only the provided relationship types and properties in the schema.\nDo not use any other relationship types or properties that are no

[llm/end] [1:chain:GraphCypherQAChain > 4:chain:LLMChain > 5:llm:ChatOpenAI] [30.74s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "Here are all the paths from node 2519 to node 10026 for nodes of type node_2:\n\n1. 2519 -> 1221 -> 38803 -> 4826 -> 4608 -> 10026\n2. 2519 -> 1221 -> 38803 -> 1221 -> 4608 -> 10026\n3. 2519 -> 1221 -> 38803 -> 1221 -> 4637 -> 1221 -> 4608 -> 10026\n4. 2519 -> 1221 -> 4608 -> 10026\n5. 2519 -> 1221 -> 4637 -> 1221 -> 38803 -> 4826 -> 4608 -> 10026\n6. 2519 -> 1221 -> 4637 -> 1221 -> 38803 -> 1221 -> 4608 -> 10026\n7. 2519 -> 1221 -> 4637 -> 1221 -> 4608 -> 10026\n\nThese are all the possible paths from node 2519 to node 10026 for nodes of type node_2.",
        "generation_info": {
          "finish_reason": "stop"
        },
        "type": "ChatGeneration",
        "message": {
          "lc": 1,
          "type": "constructor",
          "id": [
            "langchain",
            "schema",
            "messages",
   

'Here are all the paths from node 2519 to node 10026 for nodes of type node_2:\n\n1. 2519 -> 1221 -> 38803 -> 4826 -> 4608 -> 10026\n2. 2519 -> 1221 -> 38803 -> 1221 -> 4608 -> 10026\n3. 2519 -> 1221 -> 38803 -> 1221 -> 4637 -> 1221 -> 4608 -> 10026\n4. 2519 -> 1221 -> 4608 -> 10026\n5. 2519 -> 1221 -> 4637 -> 1221 -> 38803 -> 4826 -> 4608 -> 10026\n6. 2519 -> 1221 -> 4637 -> 1221 -> 38803 -> 1221 -> 4608 -> 10026\n7. 2519 -> 1221 -> 4637 -> 1221 -> 4608 -> 10026\n\nThese are all the possible paths from node 2519 to node 10026 for nodes of type node_2.'

In [8]:
chain.run("""
Return all paths from node 4651 to node 1136 for nodes of type node_2
""")

[chain/start] [1:chain:GraphCypherQAChain] Entering Chain run with input:
{
  "query": "\nReturn all paths from node 4651 to node 1136 for nodes of type node_2\n"
}
[chain/start] [1:chain:GraphCypherQAChain > 2:chain:LLMChain] Entering Chain run with input:
{
  "question": "\nReturn all paths from node 4651 to node 1136 for nodes of type node_2\n",
  "schema": "Node properties are the following: \n {'Node': [{'property': 'id', 'type': 'STRING'}, {'property': 'as_name', 'type': 'STRING'}, {'property': 'org_name', 'type': 'STRING'}, {'property': 'country', 'type': 'STRING'}, {'property': 'upstream', 'type': 'STRING'}, {'property': 'downstream', 'type': 'STRING'}, {'property': 'rank', 'type': 'STRING'}, {'property': 'city', 'type': 'STRING'}, {'property': 'state', 'type': 'STRING'}], 'Node_2': [{'property': 'id', 'type': 'STRING'}, {'property': 'as_name', 'type': 'STRING'}, {'property': 'org_name', 'type': 'STRING'}, {'property': 'country', 'type': 'STRING'}, {'property': 'upstream', 'typ

'The paths from node 4651 to node 1136 for nodes of type node_2 are as follows:\n1. Node 4651 (THAI-GATEWAY) connects to Node 9737 (TOTNET-TH-AS-AP), which in turn connects to Node 1136 (KPN B.V.).\n2. Node 4651 (THAI-GATEWAY) also directly connects to Node 1136 (KPN B.V.).\nThese are the two paths from node 4651 to node 1136 for nodes of type node_2.'